# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User: sha512

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        user_provider:
            id: AppBundle\Security\User\AdminUserProvider

    firewalls:
        app:
            pattern: /(.*)
            provider: user_provider
            form_login:
                login_path:     security_login
                check_path:     security_check
                always_use_default_target_path: true
                default_target_path: dashboard
                csrf_token_generator: security.csrf.token_manager
            logout:
                path:           security_logout
                target:         security_login
            anonymous: true
            remember_me:
                secret:   '%secret%'
                lifetime: 14400 # 4 hours in seconds
                path:     /

        main:
            pattern: ^/
            anonymous: ~

    access_control:
        - { path: ^/_wdt|_profiler|translations|js, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles:  IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_check, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/password-request, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/password-reset, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout, role: IS_AUTHENTICATED_ANONYMOUSLY }


    role_hierarchy:
        ROLE_ADMIN:       [ROLE_ADMIN]

