<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Comment;
use AppBundle\Entity\Place;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    private function getPlacesQuery(Place $place)
    {
        $query = $this->createQueryBuilder('c');
        $query->OrWhere('(c.parentEntity = :class_name AND c.parentId = :place_id)')
            ->setParameter('class_name', Place::class)
            ->setParameter('place_id', $place->getId());
        return $query;
    }

    public function getCommentsTree(Place $place)
    {
        $query = $this->getPlacesQuery($place);
        $ids = $query->getQuery()->getArrayResult();
        $query = $this->getPlacesQuery($place);

        if(count($ids) > 0) {
            $keys = implode(', ', array_column($ids, 'id'));
            $query->OrWhere('(c.parentEntity = :comments AND c.parentId IN (:keys))')
                ->setParameter('comments', Comment::class)
                ->setParameter('keys', $keys);
        }
        $query->orderBy('c.createdAt');

        return $query->getQuery()->getResult();
    }
}
